### ISSUE TITLE
Sound Null Safety Support

### ISSUE THREAD

**Issue by Rockvole** [TemplarVolk/ADLER32#1]
Thanks for this useful library.

Would it be possible for you to update this library to support null safety in the newer version of dart ?

You probably would just need to replace a few int with int?

Thank-you.

**Comment by Rockvole** [comment]
I added a pull request :
https://github.com/luaVolk/ADLER32/pull/2

**Comment by luaVolk** [comment]
Sorry for not getting back to you sooner.
I have merged your changes. Thank you for contributing.

**Comment by Rockvole** [comment]
Hi LuaVolk,
Thanks for pulling my changes. Unfortunately dart publish gives an error if I try to publish from github.
Please can you publish ?

```
Package validation found the following potential issue:
* Don't depend on "adler32" from the git source. Use the hosted source instead. For example:
  
  dependencies:
    adler32: ^1.0.0
  
  Using the hosted source ensures that everyone can download your package's dependencies along with your package.
```

**Comment by luaVolk** [comment]
i have published the new version.

**Comment by Rockvole** [comment]
Thank-you, mine is published now :

https://pub.dev/packages/rockvole_db_replicator
